title: PARHAM MAYSAMI-AZAD's Blog
author: Parham Maysami-Azad
email: pmays2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Hi! Welcome to my site! Here I will talk about my experiences in ICS!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
